Testy junit
Selethen/Java-Course pull request #1
Opened 2016-12-21 19:08 UTC by Selethen

2016-12-22 19:22 UTC, piskunop requested changes

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/Testy/programTest.java
> +public class programTest {
powinno być ProgramTest

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/Testy/programTest.java
> +	public void testHighestButOneLiczbyDodatnie() {
proponuję się zdecydować na angielski. Mix PL-En wygląda bardzo dziwnie.
Komentarze mogą zostać PL

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/Testy/programTest.java
> +		for (int i = 0; i < 10000; i++)
staraj sie zawsze pisać pętle z nawiasami {}, pomienięcie nawiasów jest bardzo błędogenne
w tym przypadku można użyć foreach

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/Testy/programTest.java
> +package Testy;
Dopisałeś sporo testów, brawo!!

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/Testy/programTest.java
> +		assertFalse("b��d w przypadku podania znak�w specjalnych", Program.isNumber(new String("^%$#&@")));
Nie trzeba pisać new String("abc")
można poprostu podać "abc"

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/randomProgramy/Program.java
> -				if (list.get(i) != list.get(i + 1)) {
przypomnij mi żebyśmy o tym pogadali.
to jest sedno javy

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/randomProgramy/Program.java
> +			for (int i = 1; i < s.length(); i++) {
tu też można foreach

2016-12-22 19:22 UTC, piskunop commented on Java Course/src/randomProgramy/Program.java
> +	public static boolean isNumber(String s) {
narazie przymykam oko na to, że metoda walidująca zwraca bookean.
Ale wrócimy do tego tak się nie robi.

2016-12-22 19:36 UTC, Selethen commented
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
A jak w tych obydwu przypadkach u¿yæ foreach? W pierwszym dopiero tworzê listê, a w drugim zaczynam od drugiego znaku bo pierwszy sprawdzam osobno.
 
Dnia Czwartek, 22 Grudnia 2016 20:22 piskunop <notifications@github.com> napisa³(a)

@piskunop requested changes on this pull request.

In Java Course/src/Testy/programTest.java:
> +import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.List;
+import java.util.Random;
+
+import org.junit.Test;
+
+import randomProgramy.Program;
+
+/**
+ * Testy do programu zwracaj�cego przednajwi�ksza liczb� ca�kowit� z podanych
+ * 
+ * @author Selethen
+ *
+ */
+public class programTest {

powinno byæ ProgramTest

In Java Course/src/Testy/programTest.java:
> +
+import randomProgramy.Program;
+
+/**
+ * Testy do programu zwracaj�cego przednajwi�ksza liczb� ca�kowit� z podanych
+ * 
+ * @author Selethen
+ *
+ */
+public class programTest {
+
+	/**
+	 * Testowanie metody highestButOne w przypadku podania tylko liczb dodatnich
+	 */
+	@Test
+	public void testHighestButOneLiczbyDodatnie() {

proponujê siê zdecydowaæ na angielski. Mix PL-En wygl±da bardzo dziwnie. Komentarze mog± zostaæ PL

In Java Course/src/Testy/programTest.java:
> +				-2147483643, -2147483642, -2147483641, -2147483640, -2147483639, -2147483638, -2147483637, -2147483636,
+				-2147483635, -2147483634, -2147483633);
+		assertEquals("b�ad w przypadku liczb dodatnich i ujemnych", new Integer(-2147483634),
+				Program.highestButOne(list4));
+	}
+
+	/**
+	 * Testowanie metody highestButOne w przypadku podania bardzo du�ej ilo�ci
+	 * danych
+	 */
+	@Test
+	public void testHighestButOneALotOfData() {
+		Random generator = new Random();
+
+		List<Integer> list1 = new ArrayList<>();
+		for (int i = 0; i < 10000; i++)

staraj sie zawsze pisaæ pêtle z nawiasami {}, pomieniêcie nawiasów jest bardzo b³êdogenne w tym przypadku mo¿na u¿yæ foreach

In Java Course/src/Testy/programTest.java:
> @@ -0,0 +1,214 @@
+package Testy;

Dopisa³e¶ sporo testów, brawo!!

In Java Course/src/Testy/programTest.java:
> +	/**
+	 * Testowanie metody isNumber w przypadku podania liczb
+	 */
+	@Test
+	public void testIsNumberNumbers() {
+		assertTrue("b��d w przypadku podania liczby dodatniej", Program.isNumber(new String("2147483647")));
+		assertTrue("b��d w przypadku podania liczby ujemnej", Program.isNumber(new String("-2147483646")));
+	}
+
+	/**
+	 * Testowanie metody isNumber w przypadku podania liczb ze znakami
+	 * specjalnymi
+	 */
+	@Test
+	public void testIsNumberInvalidData() {
+		assertFalse("b��d w przypadku podania znak�w specjalnych", Program.isNumber(new String("^%$#&@")));

Nie trzeba pisaæ new String("abc") mo¿na poprostu podaæ "abc"

In Java Course/src/randomProgramy/Program.java:
> @@ -77,12 +79,32 @@ public static Integer highestButOne(List<Integer> list) {
 			return list.get(1);
 		else {
 			for (i = 0; i < list.size() - 1; i++) {
-				if (list.get(i) != list.get(i + 1)) {

przypomnij mi ¿eby¶my o tym pogadali. to jest sedno javy

In Java Course/src/randomProgramy/Program.java:
>  					return list.get(i + 1);
 				}
 
 			}
 		}
 		return null;
 	}
+
+	/**
+	 * Funkcja sprawdza czy w danym stringu znajduj� si� tylko cyfry lub
+	 * ewentualnie minus na pocz�tku
+	 * 
+	 * @param s
+	 * @return true kiedy s� tylko cyfry lub minus na pocz�tku, false kiedy sa
+	 *         inne znaki
+	 */
+	public static boolean isNumber(String s) {
+		if ((s.charAt(0) < '0' || s.charAt(0) > '9') && s.charAt(0) != '-')
+			return false;
+		else {
+			for (int i = 1; i < s.length(); i++) {

tu te¿ mo¿na foreach

In Java Course/src/randomProgramy/Program.java:
>  					return list.get(i + 1);
 				}
 
 			}
 		}
 		return null;
 	}
+
+	/**
+	 * Funkcja sprawdza czy w danym stringu znajduj� si� tylko cyfry lub
+	 * ewentualnie minus na pocz�tku
+	 * 
+	 * @param s
+	 * @return true kiedy s� tylko cyfry lub minus na pocz�tku, false kiedy sa
+	 *         inne znaki
+	 */
+	public static boolean isNumber(String s) {

narazie przymykam oko na to, ¿e metoda waliduj±ca zwraca bookean. Ale wrócimy do tego tak siê nie robi.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Selethen/Java-Course","title":"Selethen/Java-Course","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/Selethen/Java-Course"}},"updates":{"snippets":[{"icon":"PERSON","message":"@piskunop requested changes on #1"}],"action":{"name":"View Pull Request","url":"https://github.com/Selethen/Java-Course/pull/1#pullrequestreview-14053820"}}}
// ]]>


 

2017-01-06 18:22 UTC, piskunop requested changes

2017-01-06 18:22 UTC, piskunop commented on Java Course/src/randomProgramy/Program.java
> +			if (list.get(0) != list.get(1))
Łukasz!!!!!! tak nie wolno!!!!!!
list jest typu: List<Integer> a co to oznacza, proponuję pogadać o tym przez telefon.

2017-01-06 18:22 UTC, piskunop commented on Java Course/src/randomProgramy/Program.java
> +		if ((s.charAt(0) < '0' || s.charAt(0) > '9') && s.charAt(0) != '-')
nawiasy, please....

2017-01-06 18:22 UTC, piskunop commented on Java Course/src/randomProgramy/Program.java
> +				if (s.charAt(i) < '0' || s.charAt(i) > '9')
nawiasy, nawiasy

2017-01-15 14:00 UTC, merged